### ISSUE TITLE
ux bug when selecting month / year while in dark mode

### ISSUE THREAD

**Issue by ralphtheninja** [webxdc/calendar#81] opened 2023-06-29 00:22 UTC
How to reproduce:

1. Click the hamburger menu in top left corner
2. Select the month or year drop downs
3. List is shown in white with white text?

![Screenshot_20230629_021819_Delta Chat](https://github.com/webxdc/calendar/assets/308049/01bd43f7-2ff5-48ca-86e5-ee58b2289962)
![Screenshot_20230629_021810_Delta Chat](https://github.com/webxdc/calendar/assets/308049/f4058354-7b18-4fa2-914f-c16d453f0d7f)

**Comment by ralphtheninja** [comment] 2023-06-29 00:23
Side note. What determines whether the calendar is shown in dark or light mode?

**Comment by r10s** [comment] 2023-06-29 18:40
it is an android issue, no bug the xdc.

the issue is fixed in android already, see https://github.com/deltachat/deltachat-android/pull/2600 and https://github.com/deltachat/deltachat-android/pull/2601, this will go to the next release. there is no actionable item for the calendar.xdc here.

> Side note. What determines whether the calendar is shown in dark or light mode

[in the css](https://github.com/webxdc/calendar/blob/main/calendar.css#L237), `color-scheme` tells the browser/webview that dark mode is okay as well, the following media selectors tweak the colors then.

(on android, the browser/webview uses the system's dark/light settings (not delta chat's) however, in most cases, this seems good enough. desktop uses "themes", so also here system's dark/light settings is probably good enough. ios always just uses the system's dark/light setting, so there is no confusion possible at all)

**Closed** 2023-06-29 18:54 UTC
Labels: bug
