### ISSUE TITLE
month/year select is white-on-white in some androids dark mode

### ISSUE THREAD

**Issue by r10s** [webxdc/calendar#74] opened 2023-06-24 07:48 UTC
cc @adbenitez to provide more information

**Comment by adbenitez** [comment] 2023-06-24 11:18
this is not a bug of the Calendar app, this happens in any webxdc app using a "select" tag, and it happens on Android only, because our android app doesn't properly apply the dark theme, we probably miss some definitions, this issue should be transferred there

**Closed** 2023-06-25 18:44 UTC
Labels: bug
