### ISSUE TITLE
sometimes there is an off by one error on importing

### ISSUE THREAD

**Issue by Simon-Laux** [webxdc/calendar#12] opened 2023-05-29 10:08 UTC
when exporting and importing the events sometimes are all one day earlier.

<img width="703" alt="Bildschirmfoto 2023-05-29 um 12 07 31" src="https://github.com/webxdc/calendar/assets/18725968/7a595f4f-c9b1-449d-8571-89903ab0457c">

**Comment by r10s** [comment] 2023-05-29 14:41
cmp. https://github.com/webxdc/calendar/issues/3 - i did not dived into the issue that time

**Comment by r10s** [comment] 2023-06-05 19:07
so, i dived a bit into that:

in  `doAddEvent()` there is `dateSt = new Date(cal.selYear, cal.selMonth, cal.selDay)` that should create a date according to local time.

a few lines below, that date is converted to a unix timstamp that is sent via update using `dateSt.getTime()` - and that is already off-by-one.

the error seems to be compensated on receiving updates.

i do not undertstand the error fully yet, might even be a bug in javascript, cmp.
https://stackoverflow.com/questions/9509360/datepicker-date-off-by-one-day

**Comment by r10s** [comment] 2023-06-05 20:01
the issue is that we're using "midnight, local time" for the all-day-events (eg. 2023-06-05 00:00:00 GMT+2) that are converted to UTC for updates/ics (2023-06-01 22:00:00 UTC), this is okayish, one can do so

but on importing ics, we just truncate the UTC time before creating an UTC timestamp - therefore, depending on the timezone one day is lost.

to be clear: this has nothing to do with ppl being in different timezones, if this is true, this raises [general issues with all-day-events](https://duckduckgo.com/?q=calendar+all+day+events+different+timezones&t=osx&ia=web) and enhancing that is out of scope of this issue

**Comment by r10s** [comment] 2023-06-05 21:15
> this has nothing to do with ppl being in different timezones,

to  mitigate that hugely, we could say that the "whole day events" are noon, not midnight. then, summer/winter time would not shift things around - and also many neighboring timezones are fine

**Closed** 2023-06-07 10:02 UTC
Labels: bug, import/export
